#!/usr/bin/env node
/**
 * lumina-close — the runnable Stage-4 loop closer.
 *
 * Reads the registry + ledger + persisted system state, derives proposals
 * (skipping already-resolved targets), compiles them into candidates, runs them
 * through the evaluation harness, and AUTO-APPLIES the `auto`-tier promotions:
 * the resolution events are appended to the ledger and the new values are written
 * to lumina-state.json. Everything else is deferred with a reason.
 *
 *   node scripts/lumina-close.mjs            # apply auto-promotions
 *   node scripts/lumina-close.mjs --dry-run  # report only, persist nothing
 *
 * This is the inner loop closing without a human: observe → score → propose →
 * evaluate → apply, bounded by gates and invariants. Re-running is idempotent —
 * resolved targets are excluded, so settled questions are never re-applied.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import {
  products,
  parseLedger,
  appendEvent,
  proposeImprovements,
  computeFitness,
  fitnessGate,
  checkGate,
  closeLoop,
  resolvedTargetsFromValues,
  metaReview,
} from "../packages/lumina-system/dist/index.js";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ledgerPath = resolve(root, "lumina-ledger.jsonl");
const statePath = resolve(root, "lumina-state.json");
const reportPath = resolve(root, "docs/system/close-report.md");
const dryRun = process.argv.includes("--dry-run");

const ledgerText = readFileSync(ledgerPath, "utf8");
const events = parseLedger(ledgerText);
const values = existsSync(statePath) ? JSON.parse(readFileSync(statePath, "utf8")) : {};

const resolvedTargets = resolvedTargetsFromValues(values);
const proposals = proposeImprovements(events, products, { resolvedTargets });

const baseline = { products, events, values };
const gates = [fitnessGate(), checkGate("no-new-clash", (s) => !s.events.some((e) => e.kind === "clash"))];

const close = closeLoop(baseline, proposals, gates);

const baseScore = computeFitness(baseline.events, baseline.products).metrics.score;
const afterScore = computeFitness(close.state.events, close.state.products).metrics.score;

// ── Meta circuit breaker (Stage 5) ────────────────────────────────────────────
// The meta-loop can halt auto-application when the gameable fitness has drifted
// from the un-gameable holdout (Goodhart). The closer honors that here.
const review = metaReview(events, products, resolvedTargets);
const frozen = review.freezeAutoPromotion;

// ── Persist (unless dry-run or frozen) ────────────────────────────────────────
if (!dryRun && !frozen && close.applied.length > 0) {
  let nextLedger = ledgerText;
  for (const e of close.newEvents) nextLedger = appendEvent(nextLedger, e);
  writeFileSync(ledgerPath, nextLedger);
  writeFileSync(statePath, JSON.stringify(close.state.values, null, 2) + "\n");
}

// ── Report ────────────────────────────────────────────────────────────────────
const now = new Date().toISOString();
const md = `# Lumina Loop-Close Report

_Generated ${now}${dryRun ? " (dry run — nothing persisted)" : ""} · ${proposals.length} open proposals · fitness ${baseScore} → ${afterScore}/100._

> Auto-generated by \`scripts/lumina-close.mjs\`. Do not edit by hand.

## Applied (auto-tier, gates clear)

${
  close.applied.length === 0
    ? "_None this cycle._"
    : close.applied
        .map((id) => `- \`${id}\` — resolution event appended, target marked resolved.`)
        .join("\n")
}

## Deferred

${
  close.deferred.length === 0
    ? "_None._"
    : `| Candidate | Verdict | Reason |\n|---|---|---|\n${close.deferred
        .map((d) => `| \`${d.candidateId}\` | ${d.verdict} | ${d.reason} |`)
        .join("\n")}`
}

---

_Only \`auto\`-tier candidates that pass every gate and touch no invariant are applied. \`review\` / \`human-gated\` land in the approval queue; regressions and invariant mutations are rejected. Resolved targets are excluded from future cycles._
`;
writeFileSync(reportPath, md);

// ── Console ───────────────────────────────────────────────────────────────────
console.log(`Lumina close${dryRun ? " (dry run)" : ""} — fitness ${baseScore} → ${afterScore}/100  (holdout ${review.holdout}, divergence ${review.divergence})`);
if (frozen) {
  console.log(`  🧊 FROZEN by meta-guard — divergence ${review.divergence} ≥ threshold; auto-promotion halted.`);
}
console.log(`  Proposals: ${proposals.length}  ·  Applied: ${frozen ? 0 : close.applied.length}  ·  Deferred: ${close.deferred.length}`);
if (!frozen) for (const id of close.applied) console.log(`  ✅ applied  ${id}`);
for (const d of close.deferred) console.log(`  ⏸  ${d.verdict.padEnd(14)} ${d.candidateId}  — ${d.reason}`);
if (!dryRun && !frozen && close.applied.length > 0) {
  console.log(`\n  Persisted ${close.newEvents.length} resolution event(s) → lumina-ledger.jsonl`);
  console.log(`  Wrote lumina-state.json`);
} else if (dryRun) {
  console.log(`\n  Dry run — nothing written.`);
}
console.log(`  Report → docs/system/close-report.md`);
