#!/usr/bin/env node
/**
 * lumina-meta — the runnable Stage-5 meta-loop (Goodhart guard).
 *
 * Audits whether the inner loop's fitness score still reflects reality, on a
 * slow, human-supervised cadence. It compares the gameable fitness against an
 * un-gameable holdout (real-product signal only), raises alarms when they
 * diverge or when loop-generated `works` dominate, and emits human-gated
 * meta-proposals (re-weight the fitness function, freeze auto-promotion, tighten
 * the resolution gate). It never applies anything.
 *
 *   node scripts/lumina-meta.mjs
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import {
  products,
  parseLedger,
  resolvedTargetsFromValues,
  metaReview,
} from "../packages/lumina-system/dist/index.js";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ledgerPath = resolve(root, "lumina-ledger.jsonl");
const statePath = resolve(root, "lumina-state.json");
const reportPath = resolve(root, "docs/system/meta-report.md");

const events = parseLedger(readFileSync(ledgerPath, "utf8"));
const values = existsSync(statePath) ? JSON.parse(readFileSync(statePath, "utf8")) : {};
const resolvedTargets = resolvedTargetsFromValues(values);

const review = metaReview(events, products, resolvedTargets);
const s = review.signals;

const now = new Date().toISOString();
const md = `# Lumina Meta-Loop Report (Goodhart guard)

_Generated ${now}._

> Auto-generated by \`scripts/lumina-meta.mjs\`. Do not edit by hand.

## Metric integrity

| | Value |
|---|---|
| Inner fitness (gameable) | ${review.fitness} |
| Holdout (real-product signal only) | ${review.holdout} |
| **Divergence** | **${review.divergence}** |
| Auto-promotion | ${review.freezeAutoPromotion ? "🧊 FROZEN" : "open"} |
| Loop-generated works | ${s.selfWorks} / ${s.totalWorks} (${Math.round(s.selfResolutionRatio * 100)}%) |
| Reopened (resolved → re-reported) | ${s.reopenedTargets.length} |
| Unverified resolutions | ${s.unverifiedResolutions.length} |

## Alarms

${
  review.alarms.length === 0
    ? "_None — the metric is tracking reality._"
    : review.alarms
        .map((a) => `- **${a.code}** \`[${a.severity}]\` — ${a.detail}`)
        .join("\n")
}

## Meta-proposals (always human-gated)

${
  review.metaProposals.length === 0
    ? "_None._"
    : review.metaProposals
        .map((p) => `### ${p.id}  \`[${p.tier}]\`\n\n- **Kind:** ${p.kind}\n- ${p.detail}\n- **Evidence:** ${p.evidence.join(", ")}`)
        .join("\n\n")
}

---

_The meta-loop never auto-applies. A loop that could autonomously rewrite its own fitness function or invariants would be the ultimate Goodhart failure, so changing the objective is always a human decision. The holdout is computed only from signal the inner loop cannot write (real product feedback), so it cannot be gamed._
`;
writeFileSync(reportPath, md);

console.log(`Lumina meta-loop — fitness ${review.fitness} vs holdout ${review.holdout} (divergence ${review.divergence})`);
console.log(`  Loop-generated works: ${s.selfWorks}/${s.totalWorks} (${Math.round(s.selfResolutionRatio * 100)}%)  ·  reopened: ${s.reopenedTargets.length}`);
if (review.freezeAutoPromotion) console.log(`  🧊 Auto-promotion FROZEN (divergence ≥ threshold).`);
for (const a of review.alarms) console.log(`  🚨 ${a.code} [${a.severity}] — ${a.detail}`);
for (const p of review.metaProposals) console.log(`  📋 ${p.id} [${p.tier}] — ${p.detail}`);
if (review.alarms.length === 0) console.log(`  ✅ Metric is tracking reality; no alarms.`);
console.log(`\nReport → docs/system/meta-report.md`);
