#!/usr/bin/env node
/**
 * lumina-audit — the runnable Monitor/Analyze surface of the recursive loop.
 *
 * Reads the agent-feedback ledger (JSONL) + the product registry, scores system
 * fitness, derives bounded improvement proposals, and writes a report. Run it on
 * a schedule (or in CI) to turn `adherence-audit.md` from a one-time snapshot
 * into a living score.
 *
 *   node scripts/lumina-audit.mjs [path/to/ledger.jsonl]
 *
 * The brains live in @xlumina/system (pure, testable). This script is only the
 * file I/O the package intentionally doesn't carry.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// Runs against the built package (real JS), so the audit exercises exactly what
// consumers install. `npm run lumina:audit` builds the package first.
import {
  products,
  parseLedgerStrict,
  computeFitness,
  proposeImprovements,
} from "../packages/lumina-system/dist/index.js";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ledgerPath = resolve(root, process.argv[2] ?? "lumina-ledger.jsonl");
const reportPath = resolve(root, "docs/system/fitness-report.md");

const text = readFileSync(ledgerPath, "utf8");
const { events, skipped } = parseLedgerStrict(text);
const { metrics, hotspots } = computeFitness(events, products);
const proposals = proposeImprovements(events, products);

const now = new Date().toISOString();
const md = `# Lumina Fitness Report

_Generated ${now} from \`${process.argv[2] ?? "lumina-ledger.jsonl"}\` — ${events.length} events${
  skipped ? `, ${skipped} skipped` : ""
}._

> Auto-generated by \`scripts/lumina-audit.mjs\`. Do not edit by hand.

## Score: ${metrics.score} / 100

| Metric | Value |
|---|---|
| Events | ${metrics.events} |
| Registered products | ${metrics.products} |
| Works | ${metrics.works} |
| Friction | ${metrics.friction} |
| Clash | ${metrics.clash} |
| Error | ${metrics.error} |
| Override | ${metrics.override} |
| Gap | ${metrics.gap} |
| Override rate (per product) | ${metrics.overrideRate} |
| Cross-product duplication | ${metrics.duplication} |

## Hotspots

${
  hotspots.length === 0
    ? "_None — no negative signal recorded._"
    : `| Target | Negative signal | Products | Kinds |\n|---|---|---|---|\n${hotspots
        .map((h) => `| \`${h.target}\` | ${h.negativeSignal} | ${h.products} | ${h.kinds.join(", ")} |`)
        .join("\n")}`
}

## Proposals (${proposals.length})

${
  proposals.length === 0
    ? "_None — nothing crossed a threshold._"
    : proposals
        .map(
          (p) =>
            `### ${p.id}  \`[${p.tier}]\`\n\n- **Target:** \`${p.target}\`\n- **Action:** ${p.action}\n- **Motivation:** ${p.motivation}\n- **Reversible:** ${p.reversible}\n- **Evidence:** ${p.evidence.join(", ")}`,
        )
        .join("\n\n")
}

---

_Tiers: \`auto\` = promote when the evaluation harness shows no regression · \`review\` = an owner should eyeball it · \`human-gated\` = touches an invariant, never auto-applied._
`;

writeFileSync(reportPath, md);

console.log(`Lumina fitness: ${metrics.score}/100  (${events.length} events, ${proposals.length} proposals)`);
for (const p of proposals) {
  console.log(`  [${p.tier}] ${p.id} — ${p.action}`);
}
console.log(`\nReport written to docs/system/fitness-report.md`);
